"""Operational action tools."""

from app.database.action_store import save_agent_action


def record_agent_action(action: dict):
    """Persist an operational decision generated by an agent workflow."""
    return save_agent_action(action)
